---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/pages
  label: Pages
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - basic-page
  - home
- type: directory
  path: news
  label: News
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - news
- type: heading
  label: Navigation
- type: document
  path: content/options/navigation.json
  label: Main
upload_dir: media
public_path: https://philadelphia-votes-test.s3.amazonaws.com/media
front_matter_path: https://philadelphia-votes-test.s3.amazonaws.com/media
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: ".nuxt"
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn forestry-preview
